repository_root: "/robodata/husky_logs/CODa_bags"
dataset_output_root: "/robodata/arthurz/Datasets/CODa"
bag_date: "20230116"

#Bag Decoder Settings
gen_data: False   # Generates data files
viz_topics: True     # Republish sensor messages
verbose: True    # Debugging

sync_topics: [
  "/ouster/lidar_packets",
  "/stereo/left/image_raw/compressed",
  "/stereo/right/image_raw/compressed"
]

sensor_topics: [ 
  #OS1
  "/ouster/lidar_packets", 

  #Kinect
  "/camera/depth/image_raw/compressed",
  "/camera/rgb/image_raw/compressed",

  #FLIR
  "/stereo/left/image_raw/compressed",
  "/stereo/right/image_raw/compressed",

  #Vectornav
  "/vectornav/GPS",
  "/vectornav/IMU",
  "/vectornav/Mag",
  "/vectornav/Odom",

  #ZED
  "/zed/zed_node/depth/depth_registered",
  "/zed/zed_node/left/image_rect_color/compressed",
  "/zed/zed_node/right/image_rect_color/compressed",

  #Odometry
  "/husky_velocity_controller/odom"
]

bags_to_process: ["1673913890.bag"] #Leave empty to process all bags in directory
bags_to_traj_ids: [2] # Leave empty to assign ids in sequential order from 0
