repository_root: "/robodata/husky_logs/CODa_bags"
# repository_root: "/robodata/arthurz/Datasets/CODa_sync_bags"
dataset_output_root: "/robodata/arthurz/Datasets/CODa_cal"
bag_date: "20230130"
namespace: "coda"

#Bag Decoder Settings
gen_data: True   # Generates data files
vis_topics: True     # Republish sensor messages
verbose: False    # Debugging

# Synchronization parameters
sync_method: "HARDWARE_SYNC_METHOD"
trigger_topic: "/ouster/lidar_packets"
point_fields: "x y z i t ri" # xyz, intensity, time, ring 

sensor_topics:
  # Ouster Topics
  "/ouster/lidar_packets":
    id: "os1"
    sync: True
    save_subdir: "3d_raw/os1"
    save_ext: "bin" 
  # FLIR Topics
  "/stereo/left/image_raw/compressed":
    id: "cam0"
    sync: True
    save_subdir: "2d_raw/cam0"
    save_ext: "png" 
  "/stereo/right/image_raw/compressed": 
    id: "cam1"
    sync: True
    save_subdir: "2d_raw/cam1"
    save_ext: "png"
  # Kinect Topics
  # "/camera/rgb/image_raw/compressed":
  #   id: "cam2"
  #   sync: False
  #   save_subdir: "2d_raw/cam2"
  #   save_ext: "jpg" 
  # "/camera/depth/image_raw/compressed":
  #   id: "cam2"
  #   sync: False
  #   save_subdir: "3d_raw/cam2"
  #   save_ext: "png"
  # ZED Topics
  # "/zed/zed_node/depth/depth_registered":
  #   id: "cam3"
  #   sync: False
  #   save_subdir: "3d_raw/cam3"
  #   save_ext: "png"
  # "/zed/zed_node/left/image_rect_color/compressed":
  #   id: "cam3"
  #   sync: False
  #   save_subdir: "2d_raw/cam3"
  #   save_ext: "jpg" 
  # "/zed/zed_node/right/image_rect_color/compressed":
  #   id: "cam4"
  #   sync: False
  #   save_subdir: "2d_raw/cam4"
  #   save_ext: "jpg"
  # Vectornav Topics
  "/vectornav/GPS": 
    id: "gps"
    sync: False
    save_subdir: "poses/gps"
    save_ext: "txt"
  "/vectornav/IMU": 
    id: "imu"
    sync: False
    save_subdir: "poses/imu"
    save_ext: "txt" 
  "/vectornav/Mag": 
    id: "mag"
    sync: False
    save_subdir: "poses/mag"
    save_ext: "txt" 
  "/vectornav/Odom": 
    id: "gpsodom"
    sync: False
    save_subdir: "poses/gpsodom"
    save_ext: "txt" 
  # Husky Topics
  "/husky_velocity_controller/odom":
    id: "inekfodom"
    sync: False
    save_subdir: "poses/inekfodom"
    save_ext: "txt" 

bags_to_process: ["calibration_morning.bag",] #Leave empty to process all bags in directory
bags_to_traj_ids: [6] # Leave empty to assign ids in sequential order from 0
