repository_root: "/robodata/husky_logs/CODa_bags"
dataset_output_root: "/robodata/arthurz/Datasets/CODa_test"
bag_date: "20230116"

#Bag Decoder Settings
gen_data: False   # Generates data files
vis_topics: True     # Republish sensor messages
verbose: True    # Debugging

sensor_topics:
  # Ouster Topics
  "/ouster/lidar_packets":
    id: "os1"
    sync: True
    save_subdir: "3d_raw/os1"
    save_ext: "bin" 
  # Vectornav Topics
  "/vectornav/IMU": 
    id: "imu"
    sync: False
    save_subdir: "poses/imu"
    save_ext: "txt" 

bags_to_process: ["1673884184.bag"] #Leave empty to process all bags in directory
bags_to_traj_ids: [81] # Leave empty to assign ids in sequential order from 0
