repository_root: "/home/dynamo/AMRL_Research/repos/coda-devkit/my_things/spot/"
dataset_output_root: "/home/dynamo/AMRL_Research/repos/coda-devkit/my_things/output"
bag_date: ""

#Bag Decoder Settings
gen_data: True   # Generates data files

sync_topics: [
  "/ouster/lidar_packets",
]

sensor_topics: [
  "/ouster/lidar_packets",
  "/velodyne_points"
]

bags_to_process: "seq3_reduced.bag" #Leave empty to process all bags in directory
