repository_root: "/home/dynamo/AMRL_Research/repos/coda-devkit/my_things/121422"
dataset_output_root: "/home/dynamo/AMRL_Research/repos/coda-devkit/my_things/output"
bag_date: ""

#Bag Decoder Settings
gen_data: True   # Generates data files
viz_topics: True     # Republish sensor messages

sync_topics: [
  "/ouster/lidar_packets",
]

sensor_topics: [
  #OS1
  "/ouster/lidar_packets",
]

bags_to_process: ["1671032206.bag"] #Leave empty to process all bags in directory
bags_to_traj_ids: [42] # Leave empty to assign ids in sequential order from 0
