# indir: "/robodata/arthurz/Datasets/CODa"
indir: "/robodata/arthurz/Datasets/CODa_dev"
outdir: "."
# outdir: "/robodata/arthurz/Datasets/CODa_bbox_full"
# outdir: "/robodata/arthurz/Datasets/CODa_sem_full"
# outdir: "/robodata/arthurz/Datasets/CODa_sem_nocomp_full"

traj: 0
start_frame: 5645
num_workers: 96

# Keep same for CODa format
calibextr_subdir: "calibrations/[TRAJECTORY]/calib_os1_to_cam0.yaml"
calibintr_subdir: "calibrations/[TRAJECTORY]/calib_cam0_intrinsics.yaml"
bbox_subdir: "3d_bbox/os1/[TRAJECTORY]"
cam_subdir: "2d_raw/[CAM]/[TRAJECTORY]"