indir: "/robodata/arthurz/Datasets/CODa"
# outdir: "/robodata/arthurz/Datasets/CODa_summary"
outdir: "/robodata/arthurz/Research/coda"

traj: 11
start_frame: 1720
num_workers: 16

# Keep same for CODa format
calibextr_subdir: "calibrations/[TRAJECTORY]/calib_os1_to_cam0.yaml"
calibintr_subdir: "calibrations/[TRAJECTORY]/calib_cam0_intrinsics.yaml"
bbox_subdir: "3d_bbox/os1/[TRAJECTORY]"
cam_subdir: "2d_raw/[CAM]/[TRAJECTORY]"