annotations_input_root: "/robodata/arthurz/Datasets/CODa_annotations_raw"
annotations_output_root: "/robodata/arthurz/Datasets/CODa"

annotation_type: "deepen"

verbose: False
gen_data: False
use_wcs: True