viz_img: True
viz_pc: True
viz_3danno: False
viz_pose: False
viz_2danno: False

use_wcs: False
save_object_masks: False
object_mask_dir: "/robodata/arthurz/Datasets/ZixArt"

root_dir: "/robodata/arthurz/Datasets/CODa"

trajectory_frames:
  [600, 700] # Visualize all frames in trajectory
  # [50, 545]
  # [-1, -1]
  # [900, 1200]
  # [2760, 2809]
  # [700, 749]

downsample_rate: 1