viz_img: True
viz_pc: True
viz_3dbbox: True
viz_2dbbox: False
viz_2dterrain: True
viz_pose: True

use_wcs: False
save_object_masks: False
object_mask_dir: "/home/arthur/AMRL/Datasets/ZixArt"

root_dir: "/home/arthur/AMRL/Datasets/CODa"
sem3d_root_dir: "/home/arthur/AMRL/Datasets/CODa/3d_semantic/os1"

trajectory_frames:
  # [50, 545]
  # [-1, -1]
  # [900, 1200]
  [2760, 2809]
  # [700, 749]

downsample_rate: 1